---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-token
  namespace: testapp-keda
  annotations:
    kubernetes.io/service-account.name: keda-prometheus-reader
type: kubernetes.io/service-account-token
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: testapp-keda
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: thanos-token
    key: token
